uptrace/bun

- query_insert.go
- query_update.go
Small change per #18 to add exclude column to InsertQuery
> Add ColumnExpr and ExcludeColumn to UpdateQuery and InsertQuery

- internal/dbtest/.snapshots/TestQuery-mysql-65
- internal/dbtest/.snapshots/TestQuery-mysql-66
- internal/dbtest/.snapshots/TestQuery-pg-65
- internal/dbtest/.snapshots/TestQuery-pg-66
- internal/dbtest/.snapshots/TestQuery-sqlite-65
- internal/dbtest/.snapshots/TestQuery-sqlite-66
- internal/dbtest/query_test.go
- query_insert.go
- query_update.go
Partially reverts https://github.com/uptrace/bun/pull/19
> Remove ColumnExpr and add query tests for Value

- driver/pgdriver/config.go
> Print the whole string

- schema/table.go
Is this the only place for this check to be done? Couldn't find any other ones.
Closing #29
> Add warn log if field is zero valued time

- db.go
- query_insert.go
Example in my repo: https://github.com/j2gg0s/bun/blob/mysql/example/basic/main.go#L83
> insert: mysql does not support insert with alis

- db.go
- dialect/feature/feature.go
- dialect/pgdialect/dialect.go
- dialect/sqlitedialect/dialect.go
- internal/dbtest/.snapshots/TestQuery-mysql-22
- internal/dbtest/.snapshots/TestQuery-mysql-23
- internal/dbtest/.snapshots/TestQuery-mysql-56
- query_insert.go
Cleans up https://github.com/uptrace/bun/pull/43
@j2gg0s just FYI
> Add InsertTableAlias feature and enable it in Postgres and SQLite

- db.go
- dialect/feature/feature.go
- dialect/mysqldialect/dialect.go
- dialect/pgdialect/dialect.go
- dialect/sqlitedialect/dialect.go
- query_delete.go
- schema/dialect.go
Add `dialect.MySQL5` so we can properly test it. CC @j2gg0s
> Add MySQL5 dialect

- migrate/migrations.go
References point 2 of the #41 issue.
> add migration directory option

- migrate/migration.go
- migrate/migrations.go
Fixes https://github.com/uptrace/bun/issues/64
> Don't use alias in migrate

- migrate/migrations.go
This PR allows setting one's own logger function.
> add custom logger

- CHANGELOG.md
- example/migrate/main.go
- migrate/migration.go
- migrate/migrator.go
Updates https://github.com/uptrace/bun/issues/41
> migrate: create down SQL migration by default

- dialect/append.go
- dialect/mysqldialect/append.go
- dialect/mysqldialect/dialect.go
- dialect/pgdialect/append.go
- dialect/pgdialect/dialect.go
- dialect/sqlitedialect/dialect.go
- internal/dbtest/db_test.go
- model_map.go
- model_map_slice.go
- schema/append.go
- schema/append_value.go
- schema/dialect.go
Fixes https://github.com/uptrace/bun/issues/76
> mysqldialect: custom JSON formatter

- internal/dbtest/db_test.go
- schema/scan.go
Closes https://github.com/uptrace/bun/pull/79
> Fix scanning bool values

- README.md
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-72
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-72
- internal/dbtest/testdata/snapshots/TestQuery-pg-72
- internal/dbtest/testdata/snapshots/TestQuery-pgx-72
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-72
- query_base.go
Fixes https://github.com/uptrace/bun/issues/86
> Fix WhereGroup parenthesis

- driver/pgdriver/column.go
- driver/pgdriver/driver_test.go
Fixes https://github.com/uptrace/bun/issues/88
> driver/pgdriver: fix float64 scan

- internal/dbtest/db_test.go
- model_table_struct.go
- schema/field.go
Fixes https://github.com/uptrace/bun/issues/100
> Fix FK violation handling for SQLite3

- internal/dbtest/migrate_test.go
- migrate/migrations.go
- migrate/migrator.go
- query_table_drop.go
Fixes https://github.com/uptrace/bun/issues/99
> Fix migrations rollback

- internal/dbtest/migrate_test.go
- migrate/migrator.go
Fixes https://github.com/uptrace/bun/issues/99#issuecomment-900943633
> migrate: run migrations in reverse

- dbfixture/fixture.go
- example/fixture/fixture.yaml
- example/fixture/main.go
Fixes https://github.com/uptrace/bun/issues/59
> dbfixture: improve support for sql.Scanner

- dbfixture/fixture.go
@d-fal this should probably fix the problem with custom yaml.Unmarshaler. Could you try this code?
> dbfixture: use yaml.Unmarshaler when available

- dbfixture/encoder.go
- example/fixture/fixture.yml
- example/fixture/main.go
- schema/tables.go
Fixes https://github.com/uptrace/bun/discussions/124
> Add dbfixture.Encoder

- bun.go
Updates https://github.com/uptrace/bun/issues/131
> Add SetLogger

- driver/pgdriver/driver.go
- driver/pgdriver/driver_test.go
- driver/pgdriver/error.go
- driver/pgdriver/proto.go
Closes https://github.com/uptrace/bun/issues/141
> driver/pgdriver: retry zero writes

- dialect/mysqldialect/scan.go
- dialect/pgdialect/scan.go
- dialect/pgdialect/sqltype.go
- dialect/sqlitedialect/scan.go
- internal/dbtest/db_test.go
- internal/dbtest/pg_test.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/147
> schema: fix scanning into an interface{}

- internal/dbtest/orm_test.go
- internal/dbtest/pg_test.go
- schema/table.go
Fixes https://github.com/uptrace/bun/issues/146
> Fully skip fields marked with bun:'-'

- dialect/pgdialect/append.go
- dialect/pgdialect/array_scan.go
- dialect/pgdialect/dialect.go
- internal/dbtest/pg_test.go
- schema/append_value.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/156
> pgdialect: fix array ptr scanner and appender

- internal/dbtest/orm_test.go
- model_table_struct.go
Fixes https://github.com/uptrace/bun/issues/158
> Add nil struct check

- internal/dbtest/soft_delete_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-64
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-64
- model.go
- model_table_slice.go
- model_table_struct.go
- query_delete.go
- query_update.go
- schema/table.go
Fixes https://github.com/uptrace/bun/issues/160
> Fix bulk soft deletes

- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-82
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-82
- internal/dbtest/testdata/snapshots/TestQuery-pg-82
- internal/dbtest/testdata/snapshots/TestQuery-pgx-82
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-82
- query_insert.go
Fixes https://github.com/uptrace/bun/issues/164#issuecomment-914209319
> Append default SET form ON CONFLICT DO UPDATE queries

- .github/workflows/build.yml
- README.md
- dialect/dialect.go
- dialect/feature/feature.go
- dialect/mysqldialect/dialect.go
- dialect/pgdialect/dialect.go
- dialect/sqlitedialect/dialect.go
- extra/bunotel/otel.go
- internal/dbtest/db_test.go
- internal/dbtest/docker-compose.yaml
- internal/dbtest/migrate_test.go
- internal/dbtest/model_hook_test.go
- internal/dbtest/orm_test.go
- internal/dbtest/query_hook_test.go
- internal/dbtest/query_test.go
- internal/dbtest/soft_delete_test.go
Fixes https://github.com/uptrace/bun/issues/166
> Add support for MariaDB

- extra/bunotel/otel.go
Fixes https://github.com/uptrace/bun/issues/163#issuecomment-915222854
> fix(bunotel): set span name as early as possible

- internal/dbtest/db_test.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/172
> Copy []byte when scanning

- extra/bundebug/debug.go
Fixes https://github.com/uptrace/bun/issues/174
> chore: tweak bundebug colors

- internal/dbtest/db_test.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/175
> fix: check if table is present when appending columns

- internal/dbtest/db_test.go
- schema/table.go
- schema/zerochecker.go
Fixes https://github.com/uptrace/bun/issues/181
> fix: improve zero checker for ptr values

- internal/dbtest/db_test.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/191
> feat: add SelectQuery.Exists helper

- internal/dbtest/soft_delete_test.go
- internal/dbtest/testdata/snapshots/TestQuery-pg-26
- internal/dbtest/testdata/snapshots/TestQuery-pg-27
- internal/dbtest/testdata/snapshots/TestQuery-pg-63
- internal/dbtest/testdata/snapshots/TestQuery-pg-64
- internal/dbtest/testdata/snapshots/TestQuery-pgx-26
- internal/dbtest/testdata/snapshots/TestQuery-pgx-27
- internal/dbtest/testdata/snapshots/TestQuery-pgx-63
- internal/dbtest/testdata/snapshots/TestQuery-pgx-64
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-26
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-27
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-63
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-64
- query_update.go
Fixes https://github.com/uptrace/bun/issues/199
> fix: specify table alias for soft delete where

- driver/pgdriver/column.go
- internal/dbtest/db_test.go
- internal/dbtest/pg_test.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/196
> fix(pgdriver): return PostgreSQL DATE as a string

- dialect/append.go
- dialect/mysqldialect/append.go
- internal/dbtest/orm_test.go
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-84
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-84
- internal/dbtest/testdata/snapshots/TestQuery-pg-84
- internal/dbtest/testdata/snapshots/TestQuery-pgx-84
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-84
- schema/append.go
- schema/append_value.go
Fixes https://github.com/uptrace/bun/issues/198
> fix: don't append zero time as NULL without nullzero tag

- internal/dbtest/db_test.go
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-85
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-85
- internal/dbtest/testdata/snapshots/TestQuery-pg-85
- internal/dbtest/testdata/snapshots/TestQuery-pgx-85
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-85
- schema/field.go
- schema/table.go
Fixes https://github.com/uptrace/bun/issues/207
> fix: make allowzero work with auto-detected primary keys

- internal/dbtest/soft_delete_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-65
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-65
- internal/dbtest/testdata/snapshots/TestQuery-pg-65
- internal/dbtest/testdata/snapshots/TestQuery-pgx-65
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-65
- model_table_struct.go
- query_delete.go
Fixes https://github.com/uptrace/bun/issues/204
> fix: support soft deletes on nil model

- .github/workflows/build.yml
- db.go
- extra/bundebug/debug.go
- extra/bunotel/otel.go
- hook.go
- query_base.go
- query_select.go
- schema/sqlfmt.go
Fixes https://github.com/uptrace/bun/issues/218
> feat: add QueryEvent.Model

- driver/pgdriver/config.go
- driver/pgdriver/config_test.go
- driver/pgdriver/driver.go
- driver/pgdriver/driver_test.go
- driver/pgdriver/format.go
- driver/pgdriver/proto.go
Fixes https://github.com/uptrace/bun/issues/214
> feat(pgdriver): add Config.ConnParams to session config params

- internal/tagparser/parser.go
- internal/tagparser/parser_test.go
Fixes https://github.com/uptrace/bun/issues/222
> fix(tagparser): improve parsing options with brackets

- internal/dbtest/pg_test.go
- internal/time.go
Fixes https://github.com/uptrace/bun/issues/225
> feat: add timetz parsing

- internal/dbtest/orm_test.go
- query_select.go
- relation_join.go
Fixes https://github.com/uptrace/bun/issues/228
> fix: make ExcludeColumn work with many-to-many queries

- dialect/append.go
- dialect/mysqldialect/dialect.go
- dialect/pgdialect/append.go
- dialect/pgdialect/dialect.go
- dialect/sqlitedialect/dialect.go
- schema/append.go
- schema/append_value.go
- schema/dialect.go
- schema/sqltype.go
Fixes https://github.com/uptrace/bun/issues/168
> fix(mysqldialect): append time in local timezone

- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-87
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-88
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-87
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-88
- internal/dbtest/testdata/snapshots/TestQuery-pg-87
- internal/dbtest/testdata/snapshots/TestQuery-pg-88
- internal/dbtest/testdata/snapshots/TestQuery-pgx-87
- internal/dbtest/testdata/snapshots/TestQuery-pgx-88
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-87
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-88
- query_update.go
Fixes https://github.com/uptrace/bun/issues/232
> fix: add UpdateQuery.OmitZero

- schema/table.go
Compare sqlName and tag.Name before assign.
This maybe what we expect.
> feat(tag): log with bad tag name

- dialect/pgdialect/sqltype.go
- example/opentelemetry/README.md
- internal/dbtest/orm_test.go
- internal/tagparser/parser.go
- internal/tagparser/parser_test.go
- schema/table.go
Closes https://github.com/uptrace/bun/issues/293
> feat: support multiple tag options join:left_col1=right_col1,join:left_col2=right_col2

- README.md
- db.go
- extra/bundebug/debug.go
- extra/bunotel/otel.go
Fixes https://github.com/uptrace/bun/issues/289
> fix: call query hook when tx is started, committed, or rolled back

- dialect/pgdialect/dialect.go
- internal/dbtest/pg_test.go
Fixes https://github.com/uptrace/bun/issues/292
> fix(pgdialect): auto-enable array support if the sql type is an array

- db.go
Fixes https://github.com/uptrace/bun/issues/302
> fix: don't call rollback when tx is already done

- driver/pgdriver/error.go
- internal/dbtest/db_test.go
- internal/dbtest/orm_test.go
- internal/dbtest/pg_test.go
- query_update.go
Updates https://github.com/uptrace/bun/issues/329
> chore: add multi-update test

- internal/dbtest/db_test.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/341
> fix: change ScanAndCount to work with transactions

- db.go
- query_select.go
Updates https://github.com/uptrace/bun/issues/341
> chore: restore ScanAndCount concurrency in some cases

- extra/bundebug/debug.go
also add an option to set it to any writer
fixes #349
> change the default logoutput to stderr

- dbfixture/fixture.go
Fixes https://github.com/uptrace/bun/issues/360
> dbfixture: directly call funcs bypassing template eval

- internal/dbtest/db_test.go
- schema/table.go
Fixes https://github.com/uptrace/bun/issues/30
This requires more testing and docs.
> feat: add model embedding via embed:prefix_

- db.go
- extra/bunotel/otel.go
- hook.go
- internal/dbtest/query_hook_test.go
- query_base.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/356
> fix: add Event.QueryTemplate and change Event.Query to be always formatted

- query_index_create.go
> fix: append where to index create

- query_base.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/383
> fix: support scanning string into uint64

- internal/dbtest/db_test.go
- schema/append_value.go
Fixes https://github.com/uptrace/bun/issues/382
> fix: properly handle driver.Valuer and type:json

- internal/dbtest/orm_test.go
- model_table_slice.go
Fixes https://github.com/uptrace/bun/issues/370
> fix: check if slice is nil when calling BeforeAppendModel

- internal/dbtest/db_test.go
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-106
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-59
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-106
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-59
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-106
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-59
- internal/dbtest/testdata/snapshots/TestQuery-pg-106
- internal/dbtest/testdata/snapshots/TestQuery-pg-59
- internal/dbtest/testdata/snapshots/TestQuery-pgx-106
- internal/dbtest/testdata/snapshots/TestQuery-pgx-59
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-106
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-59
- schema/append_value.go
- schema/reflect.go
- schema/scan.go
Fixes https://github.com/uptrace/bun/issues/403
> fix: properly discover json.Marshaler on ptr field

- dialect/mysqldialect/dialect.go
- dialect/mysqldialect/version.go
- dialect/pgdialect/dialect.go
- dialect/pgdialect/version.go
- dialect/sqlitedialect/dialect.go
- dialect/sqlitedialect/version.go
- scripts/release.sh
Fixes https://github.com/uptrace/bun/issues/401
> feat: refuse to start when version check does not pass

- schema/scan.go
- schema/sqltype.go
Fixes https://github.com/uptrace/bun/issues/420
> fix: improve scan error message

- internal/dbtest/db_test.go
- query_table_create.go
Add CreateTableQuery.DetectForeignKeys method
https://github.com/uptrace/bun/issues/197
> Add CreateTableQuery.DetectForeignKeys

- dialect/feature/feature.go
- dialect/mssqldialect/dialect.go
- internal/dbtest/orm_test.go
- internal/dbtest/soft_delete_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-104
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-26
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-27
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-28
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-63
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-64
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-69
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-75
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-79
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-81
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-87
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-90
- query_update.go
fixes fot mssql soft_delete and bulk update
https://github.com/uptrace/bun/issues/429
> feat: Make soft deletes work with mssql 

- internal/dbtest/db_test.go
- query_table_create.go
still require changing previous commit messages to pass lint
Try here https://stackoverflow.com/questions/1884474/change-old-commit-message-using-git-rebase
> Merge mssql-support

- .github/workflows/build.yml
- internal/dbtest/db_test.go
- schema/append_value.go
Fixes https://github.com/uptrace/bun/issues/444
> fix: check for nils when appeding driver.Value

- query_table_create.go
> fix: do not emit m2m relations in WithForeignKeys()

- model_table_slice.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/472
> chore: remove SetCap optimization

- bun.go
- example/opentelemetry/README.md
- example/opentelemetry/main.go
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-111
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-111
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-111
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-111
- internal/dbtest/testdata/snapshots/TestQuery-pg-111
- internal/dbtest/testdata/snapshots/TestQuery-pgx-111
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-111
- schema/append.go
Fixes https://github.com/uptrace/bun/issues/483
> fix: correctly handle bun.In([][]byte{...})

- schema/table.go
Fixes https://github.com/uptrace/bun/issues/512
> fix: automatically set nullzero when there is default:value option

- driver/pgdriver/column.go
About https://github.com/uptrace/bun/issues/562
I expose `pgdriver.ParseTime`. 
Should I move the func to another package?
Could you review it ?
> feat(pgdriver): expose pgdriver.ParseTime

- internal/dbtest/orm_test.go
- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-131
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-132
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-133
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-131
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-132
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-133
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-131
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-132
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-133
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-131
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-132
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-133
- internal/dbtest/testdata/snapshots/TestQuery-pg-131
- internal/dbtest/testdata/snapshots/TestQuery-pg-132
- internal/dbtest/testdata/snapshots/TestQuery-pg-133
- internal/dbtest/testdata/snapshots/TestQuery-pgx-131
- internal/dbtest/testdata/snapshots/TestQuery-pgx-132
- internal/dbtest/testdata/snapshots/TestQuery-pgx-133
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-131
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-132
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-133
- query_select.go
#588
Here is the fix for MSSQL when offset is set to `0`.
> fix: mssql cursor pagination

- internal/dbtest/db_test.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/627
> fix: ScanAndCount without limit should select all rows

- .github/workflows/build.yml
- db.go
- internal/dbtest/db_test.go
- query_base.go
- query_raw.go
> feat: add raw query to IDB

- extra/bunotel/otel.go
> fix(bunotel): Handle option attributes

- internal/dbtest/db_test.go
- schema/table.go
> fix: support multi-level embed column

- internal/dbtest/db_test.go
- schema/append_value.go
> fix: driver.Valuer returns itself causes stackoverflow

- query_base.go
- query_column_add.go
- query_column_drop.go
- query_delete.go
- query_index_create.go
- query_index_drop.go
- query_insert.go
- query_select.go
- query_table_create.go
- query_table_drop.go
- query_table_truncate.go
- query_update.go
- query_values.go
Just fixing the `TODO` comment
> chore(query): rename to setModel

- internal/dbtest/query_test.go
- internal/dbtest/testdata/snapshots/TestQuery-mariadb-69
- internal/dbtest/testdata/snapshots/TestQuery-mssql2019-69
- internal/dbtest/testdata/snapshots/TestQuery-mysql5-69
- internal/dbtest/testdata/snapshots/TestQuery-mysql8-69
- internal/dbtest/testdata/snapshots/TestQuery-pg-69
- internal/dbtest/testdata/snapshots/TestQuery-pgx-69
- internal/dbtest/testdata/snapshots/TestQuery-sqlite-69
- query_update.go
Skip `skupupdate` fields while bulk update models
> feat(update): "skipupdate" while bulk

- query_select.go
- scripts/release.sh
Fixes https://github.com/uptrace/bun/issues/714
> fix: don't call hooks twice for whereExists

- query_merge.go
Use struct pointers since storing structs in interface{} allocates anyway.
> chore: move code around and small cleanup

- internal/dbtest/db_test.go
- model_table_slice.go
Fixes https://github.com/uptrace/bun/issues/776
Closes https://github.com/uptrace/bun/pull/777
> chore: fix scanning into a slice of ptr

- migrate/migrator.go
> feat: add option to customize Go migration template

- dialect/mysqldialect/dialect.go
Fixes https://github.com/uptrace/bun/issues/822
> fix: Allow MySQL table aliases for DELETE in >= v8.0.16

- query_base.go
- query_select.go
Fixes https://github.com/uptrace/bun/issues/835
Closes https://github.com/uptrace/bun/pull/839
> fix: run hooks on Rows

- internal/dbtest/orm_test.go
- relation_join.go
Fixes https://github.com/uptrace/bun/issues/709
> fix: Many-to-Many Relationship with extra ID field results in a scan error

- internal/dbtest/query_test.go
Since it is difficult to find out which file in the testdata/snapshots directory is associated with the query execution results of each test case in query_test.go, I assign a number for each test case.
The contents of the test cases themselves have not been changed.
> Refactor unit test of query_test.go

- internal/parser/parser_test.go
I added unit tests for parser package because it is an important feature that affects the entire Bun.
> test: add unit test for parser

- schema/table.go
- schema/table_test.go
> feat: support embed with tag Unique

- query_select.go
> fix: return error when use dest with has-many/many-to-many.

- query_select.go
> fix: apply join condition to select with count

- query_select.go
- schema/sqlfmt.go
> fix: clone query in scanAndCountConcurrently to avoid data race.

- db.go
Using the interface allows to override the `Ping` method on `*sql.DB` to implement custom health check logic, e.g. you can execute a query to check replication lag etc.
> feat: add DBReplica and use it in ReadWriteConnResolver

- schema/table.go
- schema/table_test.go
> fix(schema): process embed with struct

- schema/scan.go
resolve https://github.com/uptrace/bun/issues/1195
> feat: add support for netip.Addr and netip.Prefix

- internal/dbtest/migrate_test.go
- migrate/auto.go
Dialects assume that the byte slice always contains a single query and may be misled in case of the AutoMigrator's CreateSQLMigrations, which chains multiple SQL statements together.
For example, pgdialect checks []byte to avoid appending PRIMARY KEY clause if one is already present. In auto-migration this causes a bug: https://github.com/uptrace/bun/issues/1166#issuecomment-2908000000
The solution is to append each migration query to a fresh `[]byte` and merge them afterwards.
> fix(automigrate): append SQL to separate []byte slices

- internal/dbtest/db_test.go
- query_select.go
> fix(query): scanAndCount without model

- query_base.go
- query_delete.go
- query_insert.go
- query_merge.go
- query_select.go
- query_update.go
I saw https://github.com/uptrace/bun/issues/1204 and took a crack at implementing it. I went with the option pattern instead, but I'm happy to discuss the API
> feat: add materialize cte support 

- db.go
- internal/dbtest/db_test.go
fix: https://github.com/uptrace/bun/issues/1254
> fix: data race in db clone stats

- .github/workflows/build.yml
- .github/workflows/commitlint.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/mssql-container.yml
- .github/workflows/release.yml
- .github/workflows/stale.yml
- update actions version
- support go cache
> chore: update GitHub Actions versions
