uptrace/bun

schema/table.go
And we still does not allow delete with nil pointer model, such as :
```
-       _, err = db.NewDelete().Model(video1).Where("id = ?", video1.ID).Exec(ctx)
+       _, err = db.NewDelete().Model((*Video)(nil)).Where("id = ?", video1.ID).Exec(ctx)
```
Will we support this?
=> Allow ptr of time.Time as SoftDelete filed

example/migrate/main.go, migrate/migration.go, migrate/migrations.go, migrate/migrator.go
Updates https://github.com/uptrace/bun/issues/49
This PR
- Adds MarkDone / MarkDone to mark individual migrations
- Adds `Migrations.Sorted` to get the list of all migrations
- Adds new option `WithMigrationDryRun` that can be used with `Migrate` and `Rollback` to mark migrations as done/undone without applying them
- Adds `SelectDoneMigrations` that returns the list of migrations stored in the database
- Adds `SelectLastGroup` that returns the last migration group
@smyrman @Codebreaker101 please review
=> Add MarkDone and MarkUndone

Makefile
fixes #56 
- Bump the required `bun` version to the one to be released
- Add only .mod files
- Commit before tagging
Even though this will add only the mod files to the stage, it will commit whatever is on stage. So should there be a check that fails immediately if stage is not empty? Or when committing default to `MESSAGE` if provided so with one commit you add changes and bump the version?
=> Bump deps version on last bun release

driver/pgdriver/config.go, driver/pgdriver/driver.go
I am trying to make this great driver cleaner. I think we can use a config verifier to check all the configs and enforce some optional security checks such as minimum password length (in the case db is not being managed by dev teams).
=> some tiny cleanups to the driver

.github/dependabot.yml, .github/workflows/release.yml, Makefile, RELEASING.md, example/basic/go.mod, example/belongs-to/go.mod, example/create-table-index/go.mod, example/fixture/go.mod, example/has-many/go.mod, example/has-one/go.mod, example/many-to-many/go.mod, example/migrate/go.mod, example/model-hooks/go.mod, example/tx-composition/go.mod, scripts/release.sh, scripts/tag.sh, version.go
Fixes https://github.com/uptrace/bun/issues/56
@monkey92t @Codebreaker101 please take a look and let me know what do you think (RELEASING.md should have a brief outline). I plan to use the same script to release go-redis as well.
As the next step we can add https://github.com/softprops/action-gh-release to automatically make a GitHub release.
=> Add release.sh script

buntypes/bigint/README.md
Just happened to notice it in #113
=> Remove go-pg reference from package README

db.go, query_base.go
This is just a little addition to better support dialect specific code within transactions or functions that just want an IDB input.
=> feat: Add `Dialect()` to Transaction and IDB interface.

query_base.go, query_select.go
Fixes #364
- Minimal change for reusing an existing transaction when joining relations.
- (Minor) Fixes `IDB`/`IConn` interface checking and comments.
=> fix: reuse tx for relation join

example/opentelemetry/go.mod
Update the opentelemetry example so that it has a unique module name. Currently this example has the same name as the basic example (`github.com/uptrace/bun/example/basic`) which creates a namespace collision and may break some tools, such as `gopls` in experimental module mode.
=> fix: unique module name for opentelemetry example

internal/dbtest/db_test.go, internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mysql5-105, internal/dbtest/testdata/snapshots/TestQuery-mysql8-105, internal/dbtest/testdata/snapshots/TestQuery-pg-105, internal/dbtest/testdata/snapshots/TestQuery-pgx-105, internal/dbtest/testdata/snapshots/TestQuery-sqlite-105, schema/table.go
Enables support for anonymous fields with non-struct types.
```go
type MyString string
type A struct{
MyString // Will create a field called `my_string` with VARCHAR/TEXT type
}
```
=> feat: add anonymous fields with type name

query_base.go
Allow the user to retrieve the `IConn` from a query so that they can reuse transactions in nested queries.
```go
q.WhereGroup(sep, func(sq *bun.SelectQuery) *bun.SelectQuery {
q1 := sq.DB().NewSelect().
Conn(sq.GetConn()). // <-- reuse Conn from parent query because it might be a Tx
ColumnExpr("COUNT(*) > 0").
Model((*Activity)(nil)).
Join("JOIN assignments AS as").
JoinOn("as.activity_id = activities.id AND as.resource_id = ?", string(u))
return sq.Where("(?)", q1)
})
```
=> feat: add baseQuery.GetConn()

query_base.go
As suggested by https://github.com/uptrace/bun/pull/390#issuecomment-1004551718
Allow users to conveniently create nested queries from `*baseQuery` similarly to `IDB` values.
=> feat: create new queries from baseQuery

query_insert.go
Should we try to get last insert id only with table's pk support auto incrment?
This may make incompatible upgrade!
Or can we support some option to user?
In my case, i use string as pk.
=> feat(insert): get last insert id only with pk support auto increment

bun.go, internal/dbtest/db_test.go, internal/dbtest/model_hook_test.go, internal/dbtest/orm_test.go, internal/dbtest/pg_test.go, internal/dbtest/query_test.go, internal/dbtest/soft_delete_test.go, internal/logger.go, migrate/migration.go, migrate/migrator.go, schema/table.go
In v1.1.x the code without pk, nullzero, and autoincrement options will stop working. `nopk` and `allowzero` will be removed.
Fixes https://github.com/uptrace/bun/discussions/437
=> fix: don't automatically set pk, nullzero, and autoincrement options

schema/table.go
Some typos I saw recently, when I was having trouble with `has-many` relationship.
=> fix: fix panic message when has-many encounter an error

query_delete.go, query_select.go, query_update.go
This allows to write code like this:
```go
func addWhere(q bun.QueryBuilder) QueryBuilder {
return q.Where("id = ?", 123)
}
// Alternatively.
db.NewSelect().ApplyQueryBuilder(addWhere).Scan(ctx)
db.NewUpdate().ApplyQueryBuilder(addWhere).Exec(ctx)
db.NewDelete().ApplyQueryBuilder(addWhere).Exec(ctx)
```
=> feat: add ApplyQueryBuilder

driver/pgdriver/config.go, driver/pgdriver/config_test.go
Given a DSN using `libpq`'s `connect_timeout` parameter, parses it as `WithDialTimeout`.
closes #505
=> feat(config.go): add connect_timeout to DSN parsable params

internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-130, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-130, internal/dbtest/testdata/snapshots/TestQuery-mysql5-130, internal/dbtest/testdata/snapshots/TestQuery-mysql8-130, internal/dbtest/testdata/snapshots/TestQuery-pg-130, internal/dbtest/testdata/snapshots/TestQuery-pgx-130, internal/dbtest/testdata/snapshots/TestQuery-sqlite-130, query_update.go
Fixes https://github.com/uptrace/bun/issues/511
=> fix: fix OmitZero and value overriding

driver/pgdriver/config.go, driver/pgdriver/proto.go
This PR adds support for `sslrootcert`, as implemented by [`libpq`](https://www.postgresql.org/docs/current/libpq-ssl.html).
=> feat(config.go): add sslrootcert support to DSN parameters

extra/bunotel/option.go, extra/bunotel/otel.go
Disable formatting by default (breaing change)
and add bunotel option that enables formatting.
Formatting has potential to leak information into the traces
as such not formatting the query by default seems like
safer option.
Fixes: https://github.com/uptrace/bun/issues/546
=> feat(bunotel): add option to enable formatting of queries

internal/dbtest/db_test.go, query_table_create.go, schema/relation.go, schema/table.go
I was missing this feature from `go-pg` and wanted to add it to the codebase. AFAIK `belongs-to` is the only rel that would benefit from it, as it's the only one that generates a column on the DB. But I still don't know this repo as deeply as I want to, so feel free to correct me. 
```golang
type User struct {
ID   int    `bun:",pk,autoincrement"`
Type string `bun:",pk"`
Name string
}
type Deck struct {
ID       int `bun:",pk,autoincrement"`
UserID   int
UserType string
User     *User `bun:"rel:belongs-to,join:user_id=id,join:user_type=type,on_update:cascade,on_delete:set null"`
}
```
Also, should I tag the release for this?
=> feat: add support for ON UPDATE and ON DELETE rules on belongs-to relationships from struct tags

db.go, internal/dbtest/db_test.go, query_raw.go
Added raw query support: https://github.com/uptrace/bun/issues/593
=> feat: added raw query calls

db.go, dialect/feature/feature.go, dialect/mssqldialect/dialect.go, internal/dbtest/db_test.go, query_base.go
Updated `IDB` interface with 2 methods
```
BeginTx(ctx context.Context, opts *sql.TxOptions) (Tx, error)
RunInTx(ctx context.Context, opts *sql.TxOptions, f func(ctx context.Context, tx Tx) error) error
```
When creating a savepoint the `opts` are ignored.
Currently the transaction will not use the name but we can store something like `TX_{random}` same format as for savepoint. Then we can also emit the name with the hooks so logging libraries can show if a query is being executed as part of a transaction or savepoint.
=> feat: add tx methods to IDB (#587)

migrate/migration.go
There are inconsistencies in the receiver types on the methods of `Migration`, `MigrationGroup` and `MigrationSlice`:
- `Migration` is read-only from this package's perspective, and appears as `Migration` mostly, but the receiver is `*Migration`
- `MigrationGroup` is read-only as well from this package's perspective but it is used everywhere as `*MigrationGroup`
- `MigrationSlice` has underlying type `[]Migration` and is used as `MigrationSlice` everywhere
We stumbled upon this when trying something like (of course the following code is simplified):
```go
migrations := migrate.NewMigrations()
for _, m := range migrations.Sorted() {
fmt.Printf("migration: %s\n", m) // m does not implement fmt.Stringer since the String method is implemented on *Migration but MigrationSlice is []Migration
} …
```
=> fix(migrate): value type receivers for Migration and MigrationGroup

extra/bunotel/otel.go
Currently, even if we set attributes with `WithAttributes`, they are not set for query metrics, only pool/connections metrics. This PR fixes this issue.
=> fix: bunotel add set attributes to query metrics

driver/pgdriver/proto.go
This pull request contributes a fix for https://github.com/uptrace/bun/issues/525 that I was able to reproduce by making PostgreSQL close client connections (first revision of https://gist.github.com/htdvisser/fe1145e832fe2f323ee609e866fb59be).
Before the server closes the client connection, it sends a `57P01 terminating connection due to administrator command`. This error is however not returned by the read loops, which instead return the EOF coming from trying to read the next message.
~This pull request changes the read loops to check if there's a `firstErr` to return before returning the error returned by `readMessageType` (which in my experiment was usually a `read tcp [::1]:***->[::1]:5432: read: connection reset by peer`, but occasionally an `EOF`).~
EDIT: Updated, see comments. …
=> fix(pgdriver): return first error if readMessageType errors

driver/pgdriver/config.go, driver/pgdriver/driver.go, driver/pgdriver/driver_test.go
This pull request implements the [`SessionResetter` interface](https://pkg.go.dev/database/sql/driver#SessionResetter) on `pgdriver.Conn`.
The `SessionResetter` can be useful to detect a closed or bad connection _before_ we're trying to run queries on it. To make this work, we'd need some way to get the underlying `net.Conn` from `*pgdriver.Conn`, so I added a `Conn() net.Conn` method for that. This is similar to how `*pgx.Conn` lets you [get the underlying `*pgconn.PgConn`](https://pkg.go.dev/github.com/jackc/pgx/v4#Conn.PgConn).
=> feat(pgdriver): Implement database/sql/driver.SessionResetter

migrate/migrator.go
Cosmetic fix tbh.
The `migrator.validate()` method returned a weird looking error message: "migrate: there are no any migrations".
Updated to: "migrate: there are no migrations".
=> fix: Updates error message

query_base.go, query_delete.go, query_insert.go, query_select.go, query_update.go
close #526 
implement method `WithRecursive` for delete insert select and update query. 
```diff
+ func (q *Query) WithRecursive(name string, query schema.QueryAppender) *Query
```
for recursive query
```SQL
WITH RECURSIVE ... (
...
)
```
Ex.
```SQL
WITH RECURSIVE subordinate AS (
SELECT
c.id
FROM
categories c
WHERE
c.id = '7d82f83b-c45e-4020-8f78-dbfda314e684'
UNION
all
SELECT
c2.id
FROM
categories c2
INNER JOIN subordinate s ON s.id = c2.parent_category_id
)
SELECT
DISTINCT subordinate.*
FROM
subordinate
```
```go
subordinate := db.NewSelect().Table("categories").
Column("categories.id").
Where("categories.id = ?", id).
UnionAll(
db.NewSelect().Table("categories").
Column("categories.id").
Join("INNER JOIN subordinate ON subordinate.id = categories.parent_category_id"),
) …
```
=> feat: Add WithRecursive operation to query

internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-152, internal/dbtest/testdata/snapshots/TestQuery-mariadb-153, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-152, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-153, internal/dbtest/testdata/snapshots/TestQuery-mysql5-152, internal/dbtest/testdata/snapshots/TestQuery-mysql5-153, internal/dbtest/testdata/snapshots/TestQuery-mysql8-152, internal/dbtest/testdata/snapshots/TestQuery-mysql8-153, internal/dbtest/testdata/snapshots/TestQuery-pg-152, internal/dbtest/testdata/snapshots/TestQuery-pg-153, internal/dbtest/testdata/snapshots/TestQuery-pgx-152, internal/dbtest/testdata/snapshots/TestQuery-pgx-153, internal/dbtest/testdata/snapshots/TestQuery-sqlite-152, internal/dbtest/testdata/snapshots/TestQuery-sqlite-153, relation_join.go
When I used "Table relationships" to query, I found that the output was incorrect, and checked the logs to find that there was a problem generating the SQL statement in the soft delete position, so I fixed it.
I refer to the soft delete handling code in the `query_base.go` file.
https://github.com/uptrace/bun/blob/28915f89b0e864ee7c43782fe3234f8d65831e00/query_base.go#L806-L822
The database I use is PostgreSQL, and the model I defined is as follows:
```go
type User struct {
bun.BaseModel `bun:"user"`
ID            string    `bun:"type:TEXT,pk" json:"id"`
Name          string    `bun:"name,type:TEXT" json:"name"`
Deleted       time.Time `bun:"deleted,soft_delete" json:"-"`
Created       time.Time `bun:"created" json:"created"`
Updated       time.Time `bun:"updated" json:"updated"`
}
type …
```
=> fix: relation join soft delete SQL generate

internal/dbtest/soft_delete_test.go, query_base.go, query_delete.go
As of Bun 1.1.8, `WhereDeleted()` is ignored when used with `ForceDelete()`.
This commit fixes that problem:
```go
db.NewDelete().Model((*Model)(nil)).Where("1 = 1").WhereDeleted().ForceDelete().Exec(ctx)
// Before this commit: DELETE FROM model WHERE 1 = 1
// After this commit:  DELETE FROM model WHERE 1 = 1 AND deleted_at IS NOT NULL
```
Additionally, the `Where("1 = 1")` trick is no longer required as `WhereDeleted()` now counts as a user-defined `WHERE` clause in `mustAppendWhere`:
```go
db.NewDelete().Model((*Model)(nil)).WhereDeleted().ForceDelete().Exec(ctx)
// Before this commit: Errors with "bun: Update and Delete queries require at least one Where"
// After this commit:  DELETE FROM model WHERE deleted_at IS NOT NULL
```
This gives us an easy and natural way to hard delete all …
=> fix(query): make WhereDeleted compatible with ForceDelete

hook.go, internal/dbtest/query_hook_test.go
When writing long raw queries, it is common to use multiline strings that can start with various white space characters (`\n`, `\t`, space...). E.g.
```go
err := handle.NewRaw(`
SELECT
...
FROM
...
LEFT JOIN LATERAL (
...
) AS sub ON true
WHERE
...
`).Scan(ctx)
```
In that case, a `QueryEvent` would report its `Operation()` as `"\n\tSELECT"`.
This commit gives the ability to report `"SELECT"` instead.
Side-note: some other common cases are not handled anyway (e.g., raw queries with CTE), but this fix would still reduce the number of unexpected results.
=> Allow QueryEvent to better detect operations in raw queries

internal/util.go, util.go
When define a model like
```go
type Table struct {
bun.BaseModel 
Id int `bun:"id,pk"`
SomeValue []*CustomType `bun:",array,type:bytea[]"`
}
```
which uses pg Array with a custom type
```go
type CustomType struct {
V []byte
}
func (t *CustomType) Value() (driver.Value, error)  {
return t.V, nil
}
func (t *CustomType) Scan(src any) error {
if src == nil {
return nil
}
bytes, ok := src.([]byte)
if !ok {
return fmt.Errorf("unsupported data type: %T", src)
}
t.V = bytes
return nil
}
```
A panic will happen in the previous version ("reflect: call of reflect.Value.IsNil on struct Value" from [PtrScanner - dest.IsNil](https://github.com/uptrace/bun/blob/0b38a1c902db03906b2c71807015916269269a12/schema/scan.go#L449)).
The PR fixes the panic.
I didn't write a Unit Test but I tested locally on my …
=> fix: prevent panic when use pg array with custom database type

dialect/mssqldialect/dialect.go, dialect/mysqldialect/dialect.go, dialect/pgdialect/sqltype.go, dialect/sqlitedialect/dialect.go, go.work.sum, internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-156, internal/dbtest/testdata/snapshots/TestQuery-mariadb-157, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-156, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-157, internal/dbtest/testdata/snapshots/TestQuery-mysql5-156, internal/dbtest/testdata/snapshots/TestQuery-mysql5-157, internal/dbtest/testdata/snapshots/TestQuery-mysql8-156, internal/dbtest/testdata/snapshots/TestQuery-mysql8-157, internal/dbtest/testdata/snapshots/TestQuery-pg-156, internal/dbtest/testdata/snapshots/TestQuery-pg-157, internal/dbtest/testdata/snapshots/TestQuery-pgx-156, internal/dbtest/testdata/snapshots/TestQuery-pgx-157, internal/dbtest/testdata/snapshots/TestQuery-sqlite-156, internal/dbtest/testdata/snapshots/TestQuery-sqlite-157, query_table_create.go, schema/dialect.go
This PR fixes the handling of VARCHAR length in `CREATE TABLE`, see #736. 
Changes:
- `Dialect` implementations now need to have `DefaultVarcharLen() uint`, so that we wouldn't need to hardcode the default lengths in the dialect-specific types
- Minor refactor of `CreateAlterTable.appendSQLType`
- ~~Since `VARCHAR` can only have positive length, the signature of `CreateAlterTable.Varchar` is changed to `Varchar(n uint)`.
[This commit](df74d485f335f8a38b29b6d5d9b172513872db0f) , therefore, has a BREAKING CHANGE ❗, as this would no longer compile:~~
```golang
var n int = 4
db.NewCreateTable().Model(...).Varchar(n)
```  
Edit: breaking changes were reverted, see [this commit](https://github.com/uptrace/bun/pull/738/commits/3335e0b9d6d3f424145e1f715223a0fffe773d9a) instead.
This change is not …
=> CreateTableQuery: use correct VARCHAR length

dialect/pgdialect/append.go, go.work.sum, internal/dbtest/pg_test.go
Using `[]time.Time` with `bun:",array"` causes SQL syntax error when inserting into PostgreSQL.
The syntax error is caused by the single quotes surrounding the array, e.g `'{'2022-10-31 23:21:49.673242+00:00'}'`.
This PR fixes that by providing a custom formatter for PostgreSQL dialect that uses double quotes to surround the time instead, e.g `'{"2022-10-31 23:21:49.673242+00:00"}'`
=> feat: add support for time.Time array in Postgres

dialect/mssqldialect/dialect.go
When you want to insert model to SQL Server databases with unicode string, you have to add `N` prefix to value in insert query.
This is a sample of query:
INSERT INTO TABLE ([Name]) VALUES (N'unicodechar')
I added the `N` prefix to the MSSQL Dialect append string method.
=> Add support for inserting string values with unicode encoding for MSSQL Dialect

query_base.go, query_raw.go
The Exec(…) method allows to execute raw queries which do not return any data.
This is required in order to run queries like the following one:
```go
q2 := db.NewRaw(
`SELECT
id,
title
INTO TEMPORARY
tmp_stories_title
FROM
stories
`)
_, err = q2.Exec(ctx)
if err != nil {
panic(err)
}
```
Or to `REFRESH` a materialized view.
=> Expose Exec(…) method for RawQuery

schema/table.go
fix the panic message for "has-one", "belongs-to" and "has-many"
=> fix: incorrect table relationship panic message #791

migrate/migrations.go
Slightly modified the migration file regexp to allow flexible width digit prefixes.
=> feat: prefix migration files with 1 upto 14 digits

dialect/mysqldialect/dialect.go
close: https://github.com/uptrace/bun/pull/632
MySQL support `IN` conditions with multiple fields.
See https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_in
So, I added `feature.CompositeIn` to the features.
=> fix: enable CompositeIn for MySQL

internal/dbtest/testdata/snapshots/TestQuery-mariadb-132, internal/dbtest/testdata/snapshots/TestQuery-mariadb-137, internal/dbtest/testdata/snapshots/TestQuery-mariadb-142, internal/dbtest/testdata/snapshots/TestQuery-mysql5-132, internal/dbtest/testdata/snapshots/TestQuery-mysql5-137, internal/dbtest/testdata/snapshots/TestQuery-mysql5-142, internal/dbtest/testdata/snapshots/TestQuery-mysql8-132, internal/dbtest/testdata/snapshots/TestQuery-mysql8-137, internal/dbtest/testdata/snapshots/TestQuery-mysql8-142, query_select.go
Index hints have to be specified following a table name. 
See: https://dev.mysql.com/doc/refman/8.0/en/index-hints.html
=> fix: Index hints are not working

internal/dbtest/orm_test.go, schema/table.go
The following type has two belongs-to fields with different names (BillingAddress and ShippingAddress) but with the same type (Address):
```
type CompanyAddress struct {
Id                int `bun:",pk"`
CompanyId         int
BillingAddressId  int
BillingAddress    *Address `bun:"rel:belongs-to,join:billing_address_id=id"`
ShippingAddressId int
ShippingAddress   *Address `bun:"rel:belongs-to,join:shipping_address_id=id"`
}
```
It causes this error when making a `SELECT` (see test case):
```
sql: Scan error on column index 7, name "company_address__shipping_address__id": bun: model=Company does not have column=company_address__shipping_address__id
```
I've attached a test case to demonstrate the problem.
This commit is an attempt to fix the bug. I've narrowed it down to the …
=> fix "model does not have column" error

extra/bunotel/option.go, extra/bunotel/otel.go
Allow using a specified TracerProvider and MeterProvider instead of the global ones.
- usage:
``` go
db := bun.NewDB(sqldb, dialect, opts...)
var tp trace.TracerProvider
var mp metric.MeterProvider
// initialize tracer and meter provider
db.AddQueryHook(bunotel.NewQueryHook(bunotel.WithTracerProvider(tp), bunotel.WithMeterProvider(mp)))
```
=> feat(bunotel): add options for set otel providers of `bunotel.QueryHook`

dbfixture/encoder.go, dbfixture/fixture.go
This PR addresses the limitation where the dbfixture.New function only accepts a pointer to `bun.DB`. Both `bun.DB` and `bun.TX` implement the `IDB` interface. By allowing `dbfixture.New` to accept the `IDB` interface, we provide more flexibility, especially during testing.
close https://github.com/uptrace/bun/issues/899
=> feat: `dbfixture.New` to accept IDB interface

internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-163, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-163, internal/dbtest/testdata/snapshots/TestQuery-mysql5-163, internal/dbtest/testdata/snapshots/TestQuery-mysql8-163, internal/dbtest/testdata/snapshots/TestQuery-pg-163, internal/dbtest/testdata/snapshots/TestQuery-pgx-163, internal/dbtest/testdata/snapshots/TestQuery-sqlite-163, query_merge.go, query_update.go
Of course I can remove the second commit if that would block merging this PR!
Fixes #907
=> feat: add Join to UpdateQuery

internal/dbtest/bench_test.go, internal/dbtest/db_test.go, internal/dbtest/migrate_test.go, internal/dbtest/model_hook_test.go, internal/dbtest/mssql_test.go, internal/dbtest/orm_test.go, internal/dbtest/pg_test.go, internal/dbtest/soft_delete_test.go
While working on #926 I noticed that many tests did not properly tear down the database schema they create, which results in side-effects to other tests.
Existing tests were not affected,  but the ones I wrote for the other PR were, as they rely on having a clean schema.
In general, I think leaving no side-effects is a good unit test practice.
=> Cleanup test databases to avoid side-effects

query_base.go
This adds the `NewMerge` method to the `IDB` interface.
=> add NewMerge method to IDB

migrate/migrator.go
The migrations wouldn't run unless formatted like `tx.up.sql`, which is the correct extension according to the docs: https://bun.uptrace.dev/guide/migrations.html#sql-based-migrations
=> fix: transactional migration file extension

schema/table.go, schema/table_test.go
fix #954 by setting/asserting the alternative field name option as _alt_ instead of "alias" (in fields options) which was probably a typo in the first place, i also added a corresponding test
=> fix(table): allow alt annotation

driver/pgdriver/config.go
Adding the ServerName config allows TLS to include the ServerNameIdentification (SNI) extension. We use this at Neon to determine which database endpoint to connect to: https://neon.tech/docs/connect/connection-errors#the-endpoint-id-is-not-specified
I have tested that this works for `sslmode=require`, but I need to still confirm that this doesn't break the insecure modes from being insecure
=> enable SNI

bun.go, internal/logger.go
Currently,  `internal.Warn.Printf()` and `internal.Deprecate.Printf()` have numerous calls but no way of overriding them with your own logger.
=> Allow overiding of `Warn` and `Deprecated` loggers

schema/table.go, schema/table_test.go
This PR fixes the situation in which an `embed` tag is combined with a set of `scanonly` fields. 
This issue seems to be caused by https://github.com/uptrace/bun/commit/9052fc4cdf3a1e06facae872d0f2c12d0b1e5bfb - see the review comments below.
cc @vmihailenco
=> Fix embedded field detection

migrate/migrator.go, query_table_truncate.go
This PR fixes #960.
I implemented a ModelTableExpr method in TruncateTableQuery as well, referring to CreateTableQuery, etc.
The [Document](https://bun.uptrace.dev/guide/query-truncate-table.html#api) stated that ModelTableExpr can be used, but it is not implemented actually, so I made this modification.
I would appreciate it if you check it out!
=> feat: add ModelTableExpr to TruncateTableQuery

extra/bunzerolog/zerohook.go
Add context to the zerolog event hook so that other hooks can benefit from it, such as printing the request ID
=> add context to zerolog event hook

dialect/pgdialect/append_test.go, dialect/pgdialect/hstore_parser.go, dialect/pgdialect/hstore_parser_test.go, internal/dbtest/pg_test.go
In the current implementation of `hstore` in `github.com/uptrace/bun/dialect/pgdialect`, an empty `hstore` is encoded properly in the database as `''` but can not be retrieved.
It is handled properly for a `var md map[string]string = nil` when `NULL` is inserted in database and an empty map is returned when querying back the record, but when using a `map[string]string{}` it will insert `''` (which is expected) but will fail with the following error:
```
sql: Scan error on column index 8, name "metadata": bun: can't parse hstore: ""
```
This PR make sure an empty `hstore` is handled gracefully in the `hstoreParser` as well as adds test cases for this issues in `pgdialect` itself (for the parser AND the appender) as well as in the `internal/dbtest` package.
This fix is relatively crucial to …
=> fix: gracefully handle empty hstore in pgdialect

schema/tables.go
We receive panic `fatal error: sync: unlock of unlocked mutex` on fixtures loading.
=> Fix: Remove duplicated mutex unlock

driver/pgdriver/driver.go, driver/pgdriver/driver_test.go
This PR adds support for non-default transaction isolation level as per [Discussion](https://github.com/uptrace/bun/discussions/1033)
=> feat: add non-default transaction isolation level support to pgdriver

schema/table.go
"column" option removed here: https://github.com/uptrace/bun/commit/9052fc4cdf3a1e06facae872d0f2c12d0b1e5bfb#diff-abecd8d935ca8952a3554e15fa6989972dd0cea6de3410b6541931883b0d6d84L314
It would be nice to return it.
=> Fix: return column option back

query_select.go
If there is no limit and offset, we can use a single query to get the count and scan, the additional count query is not necessary.
```go
// If there is no limit and offset 
bundb.NewSelect().Model(users).Where("age > ?", 59).ScanAndCount(ctx)
// SELECT user.id, user.name, user.age FROM users WHERE user.age > 59;
// Otherwise
bundb.NewSelect().Model(users).Where("age > ?", 59).Offset(0).Limit(10).ScanAndCount(ctx)
// SELECT user.id, user.name, user.age FROM users WHERE user.age > 59;
// SELECT COUNT(*) FROM users WHERE user.age > 59;
```
In this way, we can use the more general repos layer method definition, like this:
```go
type UsersRepo interface {
// Implemention:
//
// var users []*models.User
// query := r.bdb.NewSelect().Model(&users)
// for _, mod := range mods {
//     query = …
```
=> pref: Optimize select query performance when there is no limit and offset

dialect/pgdialect/sqltype.go
Tested with this concise official example with connection setup changed to PostgreSQL:
https://github.com/uptrace/bun/blob/6c83b05f27c70bf3aff7df90886743b7e313927e/example/fixture/main.go#L34-L55
Without this fix, `sql.NullString` gets treated as a custom struct and then mapped to JSONB, resulting in failed insertion operations after the table has been created.
(Also removed currently unused, extraneous types.)
=> fix: sql.NullString mistaken as custom struct

query_select.go
Implements workaround from https://stackoverflow.com/a/36156953 for all backends supporting `feature.OffsetFetch` from ISO/ANSI SQL:2008, which specifies `ORDER BY` as a requirement. This should be tested further if more backends are to be added (such as Oracle in #995 – this feature is not enable there, and there seems to be an impact noted by https://stackoverflow.com/q/48620590 and https://stackoverflow.com/q/59864964).
Closes #811
=> fix: allow Limit() without Order() with MSSQL

internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-167, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-167, internal/dbtest/testdata/snapshots/TestQuery-mysql5-167, internal/dbtest/testdata/snapshots/TestQuery-mysql8-167, internal/dbtest/testdata/snapshots/TestQuery-pg-167, internal/dbtest/testdata/snapshots/TestQuery-pgx-167, internal/dbtest/testdata/snapshots/TestQuery-sqlite-167, schema/table.go
Broken since v1.2.0~9 but previously untested.
=> fix: restore explicit column: name override

internal/dbtest/orm_test.go, model_table_m2m.go, relation_join.go
This PR adds support for M2M relations with composite keys. This feature was probably supposed to be working previously, but was not tested and [turned out](https://github.com/uptrace/bun/issues/992) to be buggy. Existing functionality is not affected, according to the tests.
Commits:
- **fix(m2m join): don't query join columns**
- **fix(m2m): enforce ordering of PKs of base table**
- **fix(m2m): remove unneeded appending to struct key**
- **fix(m2m): correctly infer which columns belong to which model**
- **feat: add test for M2M relations with composite keys**
Closes https://github.com/uptrace/bun/issues/992.
=> Fix M2M relations for models with composite keys

model_table_has_many.go
Fixed 2 issues.
1. Incorrect order of the values in the structKey (they were read in the order of the columns and not in the join order)
2. If you have multiple relationships that use the column with the same name, the value in the structKey would get duplicated. Typical example partitioned tables with same partition column (year)
=> Fixed has many relationship with multiple columns

query_column_add.go, query_column_drop.go, query_delete.go, query_insert.go, query_merge.go, query_select.go, query_update.go
This pull request includes updates to the `Apply` method across multiple query types to support variadic function arguments, allowing multiple functions to be applied in sequence, these changes **will not break** existing calls.
```go
type UsersRepo interface {
// Implemention:
//
// var users []*models.User
// query := r.bdb.NewSelect().Model(&users).Apply(fns...)
// return query.ScanAndCount(ctx)
//
// Example 1:
//
//   // find users 
//   users, _, err := usersRepo.FindUsers(ctx,
//       func(sq *bun.SelectQuery) *bun.SelectQuery {
//           return sq.Where("age > ?", 59).Order("age DESC")
//       },
//       func(sq *bun.SelectQuery) *bun.SelectQuery {
//           return sq.Offset(0).Limit(100)
//       },
//   )
FindUsers(ctx context.Context, fns ...func(*bun.SelectQuery) …
```
=> feat: Enhance Apply method to accept multiple functions

README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Bun Guru](https://gurubase.io/g/bun) to Gurubase. Bun Guru uses the data from this repo and data from the [docs](https://bun.uptrace.dev/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Bun Guru", which highlights that Bun now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Bun Guru …
=> Introducing Bun Guru on Gurubase.io

dialect/pgdialect/alter_table.go, dialect/pgdialect/inspector.go, dialect/pgdialect/sqltype.go, dialect/pgdialect/sqltype_test.go, internal/dbtest/inspect_test.go, internal/dbtest/migrate_test.go, migrate/auto.go, migrate/diff.go, migrate/sqlschema/inspector.go, migrate/sqlschema/migrator.go
This PR is a follow-up with some changes I overlooked in #926:
- Rename `Inspector -> NewInspector()` and `Migrator -> NewMigrator()`
- Configure `schemaName` and `excludeTables` with `InspectorOptions`
- Rename `EquivalentType() -> CompareType()`
> Looks like we can now remove (Dialect) DefaultSchema()
While every dialect is able to set its own default schema internally, AutoMigrator needs to pass a set this for BunModelInspector explicitly.
=> Follow-up #926

internal/dbtest/docker-compose.yaml, internal/dbtest/mssql-docker/Dockerfile, internal/dbtest/mssql-docker/configure-db.sh, internal/dbtest/mssql-docker/entrypoint.sh, internal/dbtest/mssql-docker/mssql.conf, internal/dbtest/mssql-docker/setup.sql, internal/dbtest/test.sh
To fix error:
```shell
--- FAIL: TestSoftDelete/mssql2019/testSoftDeleteForce (0.00s)
db_test.go:1780: 
Error Trace:	/home/runner/work/bun/bun/internal/dbtest/db_test.go:1780
/home/runner/work/bun/bun/internal/dbtest/soft_delete_test.go:106
/home/runner/work/bun/bun/internal/dbtest/soft_delete_test.go:28
Error:      	Received unexpected error:
TLS Handshake failed: tls: failed to parse certificate from server: x509: negative serial number
Test:       	TestSoftDelete/mssql2019/testSoftDeleteForce
Messages:   	must reset model
```
=> ci: mssql use custom certificate to avoid negative serial number error

internal/dbtest/inspect_test.go, internal/dbtest/migrate_test.go, migrate/auto.go, migrate/sqlschema/inspector.go
While working on #1062 I noticed that AutoMigrator would create migration files and DB entries even when models haven't been updated and there isn't anything to migrate. This PR addresses this issue.
It also mistakenly puts _non-transactional_ migrations in `.tx.sql` files and vice versa because of a wrong value being passed to `createSQLMigrations`.
Finally, BunModelInspector should drop surrounding `''` from string literals in `bun:"default:'John Doe'"` to make the value comparable to the value retrieved from the database, i.e. a Go-string `"John Doe"`.
=> :bug: AutoMigrator: Do not create migrations if nothing to migrate

db.go, dialect/mssqldialect/dialect.go, dialect/mysqldialect/dialect.go, dialect/oracledialect/dialect.go, dialect/pgdialect/dialect.go, dialect/sqlitedialect/dialect.go, model_map_slice.go, query_base.go, query_delete.go, query_insert.go, query_table_truncate.go, query_values.go, relation_join.go
=> feat: support disable dialect's feature

internal/dbtest/db_test.go, model_table_has_many.go
Hello,
I have some trouble to use `driver.Valuer` on has many.
Here a pr, tell me if it's the wrong place
Thx !
=> fix: has many relation with driver.Valuer

schema/table.go, schema/tables.go
Hi, I found the parameter `canAddr` in `table.go`. It's passed as false during the initialization of `table.init` here:
````go
func (t *Tables) InProgress(typ reflect.Type) *Table {
if table, ok := t.inProgress[typ]; ok {
return table
}
table := new(Table)
t.inProgress[typ] = table
table.init(t.dialect, typ, false)
return table
}
````
````go
func (table *Table) init(dialect Dialect, typ reflect.Type, canAddr bool) {
table.dialect = dialect
table.Type = typ
table.ZeroValue = reflect.New(table.Type).Elem()
table.ZeroIface = reflect.New(table.Type).Interface()
table.TypeName = internal.ToExported(table.Type.Name())
table.ModelName = internal.Underscore(table.Type.Name())
tableName := tableNameInflector(table.ModelName)
table.setName(tableName)
table.Alias = table.ModelName
table.SQLAlias = …
```
=> Fix: Removed unused param on table.go and tables.go: canAddr

dialect/pgdialect/dialect.go
PostgreSQL does not support unsigned integer types. Previously, a Go uint32 type was mapped to the database integer type. When values exceeded the range, they were converted.
Even specifying the type as numeric did not prevent this conversion. This update removes the conversion, allowing the database to handle errors appropriately.
Fixed uptrace/bun#624
=> fix(pgdialect): Remove unsigned integer conversion

CONTRIBUTING.md
Thank you for creating and maintaining such an excellent library!
This pull request fixes [the incorrect link](https://github.com/go-bun/bun-docs) in the CONTRIBUTING.md file.
=> fix: replace the link to docs repo in CONTRIBUTING.md

internal/dbtest/orm_test.go, query_select.go, relation_join.go
Closes https://github.com/uptrace/bun/issues/554.
This PR introduces a new method, RelationWithOpts, to the SelectQuery interface. This method allows users to customize the JOIN ON clause when defining relationships between models (e.g., has-one, has-many).
Current Behavior: The existing Relation method allows applying filters to the joined table's SELECT query but does not modify the JOIN ON clause. For example(it is on https://github.com/uptrace/bun/issues/554):
```go
q := repo.db.NewSelect().Model(&product)
q.Relation("Stock", func(q *bun.SelectQuery) *bun.SelectQuery {
return q.Where("branch_id = ?", filter.BranchId)
})
```
- I believe it's essential to preserve this behavior to maintain backward compatibility and separation of concerns (filtering the joined table vs. customizing JOIN …
=> Add RelationWithOpts to SelectQuery for Customizing JOIN ON Clause

schema/scan.go
=> fix: support scan float32 to float32

model_table_m2m.go
=> fix: get m2m table's structKey with driver.Valuer

schema/table.go
=> feat: sort fields by struct

dialect/feature/feature.go, dialect/pgdialect/dialect.go, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-168, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-169, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-170, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-171, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-172, internal/dbtest/testdata/snapshots/TestQuery-mysql5-172, internal/dbtest/testdata/snapshots/TestQuery-mysql8-172, internal/dbtest/testdata/snapshots/TestQuery-pg-168, internal/dbtest/testdata/snapshots/TestQuery-pg-169, internal/dbtest/testdata/snapshots/TestQuery-pg-170, internal/dbtest/testdata/snapshots/TestQuery-pg-171, internal/dbtest/testdata/snapshots/TestQuery-pgx-168, internal/dbtest/testdata/snapshots/TestQuery-pgx-169, internal/dbtest/testdata/snapshots/TestQuery-pgx-170, internal/dbtest/testdata/snapshots/TestQuery-pgx-171, internal/dbtest/testdata/snapshots/TestQuery-sqlite-168, internal/dbtest/testdata/snapshots/TestQuery-sqlite-169, internal/dbtest/testdata/snapshots/TestQuery-sqlite-170, internal/dbtest/testdata/snapshots/TestQuery-sqlite-171, query_column_add.go, query_delete.go, query_update.go
With #704
I only found in the PostgreSQL documentation that it supports ADD COLUMN IF NOT EXISTS among MySQL/PostgreSQL/SQLite/SQLServer.
I’m not very familiar with this, so please let me know if my understanding is incorrect.
=> feat: add feature flag AlterColumnExists

model_table_has_many.go, model_table_m2m.go
Even if driver.Valuer is implemented, we will still directly use the field if the returned value is not suitable as a map key.
Close #1107
#1080 introduced some new features but also broke the functionality of some existing code.
To ensure compatibility, I added this *strange* logic.
=> feat: downgrade to use the field in has-many-relation

dialect/pgdialect/dialect.go, driver/pgdriver/config.go
This allow to achieve the behavior removed in https://github.com/uptrace/bun/pull/1086/files via an option
=> feat(pgdialect): allow to convert uint to int

extra/bunotel/option.go, extra/bunotel/otel.go
Bun OTEL spans would be much more informative in APM tools if their name included the primary table being queried. This could be added easily enough, however it might be nice to follow the convention used in other popular middlewares like `otelhttp` by adding a `WithSpanNameFormatter` option.
This PR allows me to add the primary query table to span names like so:
```golang
bunotel.NewQueryHook(bunotel.WithSpanNameFormatter(func(event *bun.QueryEvent) string {
name := event.Operation()
if event.IQuery != nil {
if tableName := event.IQuery.GetTableName(); tableName != "" {
name += " " + tableName
}
}
return name
}))
```
=> feat(bunotel): Ability to override span names

dialect/pgdialect/array.go, dialect/pgdialect/array_parser.go, dialect/pgdialect/array_parser_test.go, dialect/pgdialect/array_test.go, dialect/pgdialect/parser.go, dialect/pgdialect/sqltype.go, internal/dbtest/pg_test.go
Addresses issue identified in #877.
New tests added for pointers to slice and slice of pointer elements including arrays of JSONB columns.
=> fix(pgdialect): postgres syntax errors for pointers and slices #877

db.go, extra/bunexp/resolver.go, internal/dbtest/db_test.go, query_base.go
I need to make another backwards incompatible change to ReadWriteConnResolver and probably will need to make more changes before the resolver is stable. The suggested solution is to move the resolver to a new package that can be changed independently from bun.
=> chore: move ReadWriteConnResolver to bunexp

query_delete.go, query_insert.go, query_merge.go, query_select.go, query_update.go, query_values.go
I noticed that there were some methods setting the error on the query directly rather than using the provided setErr() method, so I standardized them all to use the setErr() method.
=> chore: standardize behind error setting method

.github/workflows/build.yml
Update the Go version matrix in the build workflow to include Go 1.24. This ensures that the project is tested against the latest supported Go versions.
=> chore(ci): Update Go version matrix in build workflow

internal/dbtest/db_test.go, schema/field.go, schema/relation.go, schema/table.go
Foreign keys should be created for has-one and belongs-to relations iff:
- None of the referencing columns is a primary keys
- The table is an m2m 'junction' table an all referencing columns are primary keys
See more details [in this comment](https://github.com/uptrace/bun/issues/1115#issuecomment-2661143967).
Closes #1115
=> fix(create_table): avoid creating unintended foreign keys

query_column_add.go, query_column_drop.go, query_delete.go, query_index_create.go, query_index_drop.go, query_insert.go, query_merge.go, query_raw.go, query_select.go, query_table_create.go, query_table_drop.go, query_table_truncate.go, query_update.go, util.go
This is an enhancement to recently merged comment functionality. This implementation preserves the current functionality, but allows a comment to be set at the time a query is executed.
This can be used like so:
```go
qctx := bun.ContextWithComment(ctx, "traceid:"+traceID)
err := db.NewSelect().
Model(&things).
Where("type = ?", t).
Scan(qctx)
```
Which, like the `Comment()` API will produce:
```sql
/* traceid:f2e006f2-8494-4ce6-947e-2c77f4c33dc8 */ SELECT * FROM thing WHERE type = 'whatever'
```
I should note that in this implementation, if a comment is set through a context, it takes precedence over one set on a query using the `Comment()` API. If the opposite precedence makes more sense, I'm happy to change this.
I know there was some discussion about supporting multiple comments - I'm …
=> feat: allow setting a query comment through a context value

dialect/mssqldialect/dialect.go
Add an option to support non unicode collated mssqlserver dialect.
Fixes [#824](https://github.com/uptrace/bun/issues/824), and based on [PR-828](https://github.com/uptrace/bun/pull/828), but with a global option instead of a local option
=> Add option for unicode to mssql dialect

internal/dbtest/query_test.go, internal/dbtest/testdata/snapshots/TestQuery-mariadb-187, internal/dbtest/testdata/snapshots/TestQuery-mssql2019-187, internal/dbtest/testdata/snapshots/TestQuery-mysql5-187, internal/dbtest/testdata/snapshots/TestQuery-mysql8-187, internal/dbtest/testdata/snapshots/TestQuery-pg-187, internal/dbtest/testdata/snapshots/TestQuery-pgx-187, internal/dbtest/testdata/snapshots/TestQuery-sqlite-187
Related #1154 
User's claims that CamelCase conversion is broken and that
> UserID is getting converted to user_i_d
This PR adds a test case to TestQuery suit to verify that, when running a CreateNewTable query, table/column names containing acronyms are converted to snake_case without breaking the acronyms apart, i.e. UserID -> user_id.
=> chore: add test case for acronyms

dialect/pgdialect/inspector.go, internal/dbtest/migrate_test.go, migrate/auto.go, migrate/sqlschema/inspector.go
Closes #1160 
Inspectors cannot detect foreign keys created via CreateTableQuery.ForeignKey() using reflection. This leads AutoMigrator to delete all such FKs.
The added option allows excluding manually created foreign keys from the inspection/migration scope.
=> fix(gh-1160): add WithExcludeForeignKeys option

migrate/auto.go, migrate/operations.go
Another follow up to [this comment](https://github.com/uptrace/bun/pull/926#issuecomment-2758161051) in #926:
> Also, it would be handy for migrate.comment to be an exported type. As it is, I had to use reflection to detect them.
All other operations are exported types with exported fields. We can export comment as well to make 'migrate' package more extendable / interoperable.
=> chore: rename migrate.comment to migrate.Unimplemented

dialect/pgdialect/inspector.go, internal/dbtest/inspect_test.go, internal/dbtest/migrate_test.go, migrate/diff.go, migrate/sqlschema/database.go, migrate/sqlschema/inspector.go, migrate/sqlschema/table.go
This PR addresses one of the issues raised [here](https://github.com/uptrace/bun/pull/926#issuecomment-2758161051):
> One piece of feedback regarding ordered.Map as a dependency [...] The choice to use an internal type in exported fields of exported structs made this code unusable as is, and made extending and building upon it really really messy.
Indeed, `Database`, `Table`, and `BunModelSchema` (with Tables field) are all exported members of `sqlschema` package. Having them return `internal/ordered.Map` has several implications:
1. As noted in the comment, external packages aren't able to use return of Tables(), while other methods, e.g. ForeignKeys() return usable objects. Same is true for `Columns()`.
2. Since `sqlschema` requires _dialects_ to use/return `ordered.Map`, no otherwise …
=> refactor(automigrate): Limit ordered.Map usage to migrator internals

Makefile, internal/dbtest/db_test.go, internal/dbtest/inspect_test.go, model.go, model_table_has_many.go, model_table_m2m.go, model_table_slice.go, model_table_struct.go, query_select.go
Fix a potential data race condition that could occur during relation joins. The issue stemmed
from concurrent access to the `tableModel` during the join operation. To resolve this, the `clone()` method has been implemented for the `TableModel` interface and its concrete implementations (`hasManyModel`, `m2mModel`, `sliceTableModel`, `structTableModel`). This ensures that each concurrent operation works with its own copy of the `tableModel`, preventing race conditions.
Additionally, the Makefile has been updated to include race condition detection during testing by adding the `RACETEST=1` environment variable to the `go test` command.
Fix: https://github.com/uptrace/bun/issues/1134
=> fix: relation join data race

example/migrate/main.go, example/migrate/migrations/20210505110847_bar.down.sql, example/migrate/migrations/20210505110847_bar.up.sql, internal/dbtest/migrate_test.go, migrate/auto.go, migrate/migration.go, migrate/migrations.go, migrate/migrator.go
This PR adds support for rendering `.sql` migration files as Go templates via `text/template`.  
You can now inject dynamic data into your SQL using a new migrator option: `WithTemplateData`.
Pass your data using the new option:
```go
templateData := map[string]string{
"Prefix": "example_",
}
migrator := migrate.NewMigrator(db, migrations.Migrations, migrate.WithTemplateData(templateData))
```
And in your .sql file:
```sql
CREATE TABLE {{.Prefix}}users (
id BIGINT PRIMARY KEY
);
--bun:split
ALTER TABLE {{.Prefix}}users ADD COLUMN name VARCHAR(100);
```
- `WithTemplateData(data any)` provides template data to be rendered inside .sql migration files
- `internalMigrationFunc` introduced to wrap `MigrationFunc` with template context
- `.sql` files are parsed using text/template before …
=> feat(migrations): support Go templates in SQL migrations

driver/pgdriver/listener.go, driver/pgdriver/listener_test.go, internal/dbtest/listener_test.go
This PR enables handling overflow scenarios in PostgreSQL LISTEN/NOTIFY channels by introducing a custom overflow handler option.
- Added `WithChannelOverflowHandler` option to configure custom handling of dropped messages
- Added `channelOverflowHandler` type for handling overflow notifications
- Updated channel implementation to use the overflow handler when the buffer is full
```go
ln := pgdriver.NewListener(db)
// Create a channel with custom overflow handling
ch := ln.Channel(
pgdriver.WithChannelSize(100),
pgdriver.WithChannelOverflowHandler(func(n pgdriver.Notification) {
// Handle overflow notifications:
// - Store in a database
// - Send to a dead letter queue
// - Log to a monitoring system
// - Implement retry logic
// - etc.
}),
)
```
- Provides flexibility in handling …
=> feat(pgdriver): add overflow handler to listener channel

dialect/pgdialect/alter_table.go, dialect/pgdialect/sqltype.go, dialect/pgdialect/sqltype_test.go, internal/dbtest/migrate_test.go, migrate/sqlschema/inspector.go, schema/table.go, schema/table_test.go
Closes #1159 
Related #1166 
As per the related issue, AutoMigrator creates superficial migrations for `autoincrement` columns, attempting to change type to "SERIAL" (for Postgres) and drop NOT NULL.
Because SERIAL is a create-table alias for INTEGER + generated sequence, Postgres dialect should report the two types as equivalent. Exciting addition 🎉 : when changing a column type from INTEGER to SERIAL, the dialect will also add SQL to **create a backing sequence** first and **generate default value** from it. Previously we were not handling this case correctly.
Furthermore, fields with `autoincrement` tag should have `f.NotNull = true`, because an autoincremented field cannot contain null values.
=> fix(automigrate): improve migrations on `autoincrement` columns

query_table_create.go
This PR fixes https://github.com/uptrace/bun/issues/1205
This change introduces sorting for the foreign key constraints before they are appended to the query string.
The performance impact of sorting is expected to be negligible, as the number of foreign keys on a single table is typically small.
This approach is consistent with other parts of the codebase, [CreateTableQuery.appendUniqueConstraints](https://github.com/uptrace/bun/blob/a76da0dfa562bd6e3eb1b330de954c86f8e4daf7/query_table_create.go#L273-L279), which already sorts keys to ensure deterministic output.
=> fix: sort foreign keys by name to ensure deterministic query

model_map.go, model_map_slice.go, query_table_create.go, schema/table.go
This PR migrates sorting logic from the legacy sort package to the modern slices package.
[Sorting for slices of struct values []migrate.Migration](https://github.com/uptrace/bun/blob/a76da0dfa562bd6e3eb1b330de954c86f8e4daf7/migrate/migration.go#L327-L337) has been intentionally excluded from this change, as slices.SortFunc copies the entire struct on each comparison.
Let me know if it's okay to ignore this concern.
=> refactor: use slices package for sorting

dialect/feature/feature.go, dialect/mssqldialect/dialect.go, dialect/mysqldialect/dialect.go, dialect/pgdialect/dialect.go, dialect/sqlitedialect/dialect.go, query_table_create.go, schema/table.go
Oracle does not support ON UPDATE, but when WithForeignKeys is enabled, Bun unconditionally adds ON UPDATE/ON DELETE during table creation, which causes SQL errors.
The root cause of this issue is that different dialects have different rules for foreign keys, but Bun does not account for this. Instead, it uniformly adds ON UPDATE NO ACTION and ON DELETE NO ACTION as default values.
To resolve this, we need to delegate the default values of ON UPDATE/ON DELETE to the dialect, so each one can handle it appropriately.
Since SQLite, MSSQL, MySQL, and PostgreSQL all support ON UPDATE/ON DELETE with NO ACTION as the default, the only dialect that actually requires changes is Oracle.
=> feat(dialect): return default on update/delete when create table

driver/pgdriver/format.go, driver/pgdriver/format_test.go
put spaces before negative numbers following minus signs in `format.go` to resolve CVE-2024-34359
=> fix: put spaces before negative numbers following minus signs in format.go to resolve CVE-2024-34359

driver/pgdriver/listener.go, example/pg-listen/main.go, internal/dbtest/listener_test.go
*pgdriver.Listener.Channel is not a Getter.
It`s a method that creates wrapped channel and returns channel of it.
More details [HERE](https://github.com/uptrace/bun/discussions/594#discussioncomment-13611029)
p.s. if major changes can't be accepted, i suggest to add godoc at least.
=> chore(breaking): rename Listener.Channel to Listener.CreateChannel

driver/pgdriver/listener.go, example/pg-listen/main.go, internal/dbtest/listener_test.go
The name CreateChannel suggests that you can call it multiple times to create several channels, but it won't work because listener is not concurrently safe.
=> fix: revert CreateChannel rename
